databases:
  - name: Leslie
    databaseName: budgetapp_pyzw
    user: leslie

services:
  - type: web
    name: budget-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Leslie
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false